# NumPy - Operações matmáticas com arrays

In [10]:
# Importando o NumPy
import numpy as numpy

In [11]:
arr15 = numpy.arange(1, 10)

In [12]:
print(arr15)

[1 2 3 4 5 6 7 8 9]


In [13]:
# Soma dos elementos do array 
numpy.sum(arr15)

45

In [14]:
# Retorna o produto dos elementos
numpy.prod(arr15)

362880

In [15]:
# Soma acumulada dos elementos
numpy.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [16]:
# Cria 2 arrays
arr16 = numpy.array([3, 2, 1])
arr17 = numpy.array([1, 2, 3])

In [17]:
# Soma dos arrays
arr18 = numpy.add(arr16, arr17)

In [19]:
print(arr18)

[4 4 4]


Para multiplicar duas matrizes, podemos usar a função dot() ou o operador @. Para que seja executada com sucesso, o número de colunas da primeira deve ser igual ao número de linhas da segunda matriz.

In [28]:
# Cria duas matrizes
arr19 = numpy.array([[1, 2], [3, 4]])
arr20 = numpy.array([[5, 6], [0, 7]])

In [29]:
arr19.shape

(2, 2)

In [30]:
arr20.shape

(2, 2)

In [31]:
print(arr19)

[[1 2]
 [3 4]]


In [32]:
print(arr20)

[[5 6]
 [0 7]]


In [33]:
# Multiplicar as duas matrizes
arr21 = numpy.dot(arr19, arr20)

In [34]:
print(arr21)

[[ 5 20]
 [15 46]]


 [1,2] x [5,6] = [1x5+2x0  1x6+2x7] = [5,20]
 
 [3,4]    [0,7]    [3x5+4x0  3x6+4x7]    [15,46]

In [35]:
# Multiplicar as duas matrizes
arr21 = arr19 @ arr20

In [36]:
print(arr21)

[[ 5 20]
 [15 46]]
