# NumPy - Matrizes

In [7]:
# Importando o NumPy
import numpy as numpy

In [8]:
# Criando uma matriz 
arr9 = numpy.array([[1, 2, 3], [4, 5, 6]])

In [9]:
type(arr9)

numpy.ndarray

In [10]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [11]:
print(arr9.shape)

(2, 3)


In [12]:
# Criando uma matriz 2x3 apenas com número 1
arr10 = numpy.ones((2,3))

In [13]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Lista de listas
lista = [[13, 81, 22],[0, 34, 59],[21, 48, 94]]

In [15]:
# A função matrix cria uma matriz a partir de uma lista de listas
arr11 = numpy.matrix(lista)

In [17]:
type(arr11)

numpy.matrix

In [18]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [19]:
# Formato da matriz
numpy.shape(arr11)

(3, 3)

In [20]:
# Tamanho da matriz
arr11.size

9

In [21]:
print(arr11.dtype)

int32


In [22]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [23]:
# Indexação da matriz
arr11[2,1]

48

In [24]:
arr11[1,]

matrix([[ 0, 34, 59]])

In [25]:
arr11[0:2,2]

matrix([[22],
        [59]])

In [26]:
# Alterando o elemento da matriz
arr11[1,0] = 100

In [27]:
print(arr11)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [29]:
x = numpy.array([1, 2]) # NumPy decide o tipo dos dados
y = numpy.array([1.0, 2.0]) # NumPy decide o tipo dos dados
z = numpy.array([1, 2], dtype = numpy.float64) # Força um tipo de dado específico 

In [30]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [33]:
arr12 = numpy.array([[24, 76, 92, 14], [47, 35, 89, 2]], dtype = float)

In [34]:
print(arr12)

[[24. 76. 92. 14.]
 [47. 35. 89.  2.]]


O itemsize de um array numpy é um atributo que retorna o tamanho em bytes de cada elemento do array. Ele representa o número de bytes necessários para armazenar cada valor do array numpy

In [35]:
arr12.itemsize # Tamanho em bytes de cada elemento do array

8

In [36]:
arr12.nbytes

64

In [37]:
arr12.ndim # Numero de dimensões

2