# NumPy - Funções

In [2]:
# Importando o NumPy
import numpy as numpy

In [3]:
# A função np.array() cria um array NumPy
arr2 = numpy.array([1, 2, 3, 4, 5])

In [4]:
print(arr2)

[1 2 3 4 5]


In [5]:
# Verificando o tipe do objeto
type(arr2)

numpy.ndarray

In [ ]:
# Digite . e pressione a tecla Tab para ver os MÉTODOS disponíveis em objetos NumPy
arr2.

In [6]:
# Usando métodos do array NumPy
arr2.cumprod() # Produto acumulado 

array([  1,   2,   6,  24, 120])

In [ ]:
# Digite . e pressione a tecla Tab para ver as FUNÇÕES disponíveis em objetos NumPy
numpy

In [9]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step
arr3 = numpy.arange(0, 50, 5) # Começa por 0, termina com 50, pula de 5 em 5

In [10]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [11]:
# Verificando o tipo do objeto 
type(arr3)

numpy.ndarray

In [13]:
# Formato do array 
numpy.shape(arr3)

(10,)

In [14]:
print(arr3.dtype)

int32


In [15]:
# Cria um array preenchido por zeros
arr4 = numpy.zeros(10)

In [16]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
# Retorna um nas posições em diagonal e zero no restante
arr5 = numpy.eye(3)

In [18]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# Os valores passados como parametro formam uma diagonal
arr6 = numpy.diag(numpy.array(([1, 2, 3, 4])))

In [20]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [23]:
# Array de valores booleanos
arr7 = numpy.array([True, False, False, True])

In [24]:
print(arr7)

[ True False False  True]


In [25]:
# Array de strings
arr8 = numpy.array(['Python', 'R', 'Power BI'])

In [26]:
print(arr8)

['Python' 'R' 'Power BI']


A função linspace é para criar uma sequencia de números igualmente espaçados dentro de um intervalo especificado.

In [27]:
print(numpy.linspace(0,10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [28]:
print(numpy.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


A função logspace é para criar uma sequencia de números igualmente espaçados em escala logarítima dentro de um intervalo especificado.

In [29]:
print(numpy.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]
