# NumPy - Fatiamento (slicing) de arrays

In [2]:
# Importando o NumPy
import numpy as numpy

In [3]:
# Cria um array com 3 números em diagonal
arr22 = numpy.diag(numpy.arange(3))

In [4]:
print(arr22)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [5]:
arr22[1, 1]

1

In [6]:
arr22[1] # Entende linha

array([0, 1, 0])

In [7]:
arr22[:, 2] # Se quiser coluna

array([0, 0, 2])

In [8]:
arr23 = numpy.arange(10)

In [9]:
print(arr23)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# [start:end:step]
arr23[2:9:3]

array([2, 5, 8])

In [11]:
# Cria 2 arrays
a = numpy.array([1, 2, 3, 4])
b = numpy.array([4, 2, 2, 4])

In [12]:
# Comparação item a item
a == b

array([False,  True, False,  True])

In [13]:
# Comparação global
numpy.array_equal(arr22, arr23)

False

In [14]:
arr23.min()

0

In [15]:
arr23.max()

9

In [16]:
# Somando um valor a cada elemento do array
numpy.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [17]:
# Cria um array 
arr24 = numpy.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [19]:
# Usando o método around para arredondar
arr25 = numpy.around(arr24)

In [20]:
print(arr25)

[1. 2. 2. 2. 4. 4.]


O método flatten() com NumPy é usado para criar uma cópia unidimensional ou achatada de um array multidimensional, organizado em uma única linha.

In [23]:
# Criando um array 
arr26 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [24]:
print(arr26)

[[1 2 3 4]
 [5 6 7 8]]


In [25]:
# Achatando a matriz
arr27 = arr26.flatten()

In [26]:
print(arr27)

[1 2 3 4 5 6 7 8]


In [27]:
# Criando um array
arr28 = numpy.array([1, 2, 3])

In [28]:
print(arr28)

[1 2 3]


In [29]:
# Repetindo os elementos de um array
numpy.repeat(arr28, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [31]:
# Criando um array
arr29 = numpy.array([5, 6])

In [32]:
# Criando cópia do array
arr30 = numpy.copy(arr29)

In [33]:
print(arr30)

[5 6]
