# NumPy - Arrays

https://numpy.org/

In [1]:
# Importando o NumPy
import numpy as numpy

In [2]:
numpy.__version__

'1.21.5'

In [6]:
# Array criado a partir de uma lista Python
arr1 = numpy.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [7]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [8]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [9]:
# Verificando o formato do array
arr1.shape

(9,)

In [10]:
# 1D Array = (4,)
# 2D Array = (4, 6)
# 3D Array = (4, 3, 5)

Um array NumPy é uma estrutura de dados multidimensional que fornece um objeto de matriz N-dimensional (ndarray)

# Indexação

In [16]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [11]:
# Imprimindo um elemento específico no array
arr1[4]

48

In [12]:
# Indexação (o último valor é exclusivo)
arr1[1:4]

array([21, 32, 43])

In [13]:
# Indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [14]:
# Cria uma lista de índices
indices = [1, 2, 5, 6]

In [15]:
# Imprimindo os elementos dos índices
arr1[indices]

array([21, 32, 15, 76])

In [17]:
# Cria uma máscara booleana (padrão) para os elementos pares
mask = (arr1 % 2 == 0)

In [21]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [18]:
arr1[mask]

array([10, 32, 48, 76])

In [19]:
# Alterando um elemento do array
arr1[0] = 100

In [20]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [22]:
# Não é possível incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permitida")

Operação não permitida
